### ISSUE TITLE
Interactive mode

### ISSUE THREAD

**Issue by kadel** [redhat-developer/henge#4]
Here is example of docker-compose file that is working with docker-compose but it hard get it automatically working on OpenShift/Kubernetes without user input.

```yaml
version: '2'
services:
  db:
    image: mysql:5.7
    volumes:
      - "./.data/db:/var/lib/mysql"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    links:
      - db
    ports:
      - "8000:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_PASSWORD: wordpress
```

Problem  is that this docker-compose is not saying anything about port for mysq.
Docker-compose doesn't have to do anything for ports that are used just between containers. 
Because both containers are attached to the same Docker Network, they can access any ports between them, and they can use container aliases as hostnames.

Afaik  we can't do anything similar on OpenShift :-(
Solution would be to create service for db for port 3306, but we don't know that this should be on port 3306.

So we cat ask user to provide that information during conversion.
